### ISSUE TITLE
undefined reference while make install

### ISSUE THREAD

**Issue by sherry13131** [eworm-de/journal-notify#3]
I am trying to install journal-notify, but I received the error below. I have installed these packages: libnotify4, libnotify-dev, markdown, libsystemd-dev and glib2.0. Could you tell me what am I missing?

```root@LAPTOP-IT6RQ7K4:~/journal-notify$ sudo make install
printf "#ifndef VERSION\n#define VERSION \"%s\"\n#endif\n" 0.1.1-9-gcdf84c5 > version.h
gcc -std=c11 -O2 -fPIC -Wall -Werror -lsystemd -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,-z,now -Wl,-z,relro -pie -o journal-notify journal-notify.c
/tmp/cc1yDQ88.o: In function `notify':
journal-notify.c:(.text+0x24): undefined reference to `g_markup_escape_text'
journal-notify.c:(.text+0x3f): undefined reference to `g_markup_escape_text'
journal-notify.c:(.text+0x6a): undefined reference to `notify_notification_new'
journal-notify.c:(.text+0x82): undefined reference to `notify_notification_set_timeout'
journal-notify.c:(.text+0x90): undefined reference to `notify_notification_set_urgency'
journal-notify.c:(.text+0x9a): undefined reference to `notify_notification_show'
journal-notify.c:(.text+0xad): undefined reference to `g_type_check_instance_cast'
journal-notify.c:(.text+0xb7): undefined reference to `g_object_unref'
/tmp/cc1yDQ88.o: In function `main':
journal-notify.c:(.text.startup+0x10b): undefined reference to `sd_journal_open'
journal-notify.c:(.text.startup+0x11d): undefined reference to `sd_journal_seek_tail'
journal-notify.c:(.text.startup+0x12f): undefined reference to `sd_journal_previous'
journal-notify.c:(.text.startup+0x205): undefined reference to `sd_journal_close'
journal-notify.c:(.text.startup+0x345): undefined reference to `sd_journal_add_conjunction'
journal-notify.c:(.text.startup+0x420): undefined reference to `sd_journal_add_disjunction'
journal-notify.c:(.text.startup+0x492): undefined reference to `sd_journal_add_match'
journal-notify.c:(.text.startup+0x54a): undefined reference to `sd_journal_next'
journal-notify.c:(.text.startup+0x56f): undefined reference to `sd_journal_wait'
journal-notify.c:(.text.startup+0x5d0): undefined reference to `sd_journal_get_data'
journal-notify.c:(.text.startup+0x626): undefined reference to `sd_journal_get_data'
journal-notify.c:(.text.startup+0x67c): undefined reference to `sd_journal_get_data'
journal-notify.c:(.text.startup+0x93f): undefined reference to `notify_init'
journal-notify.c:(.text.startup+0x97b): undefined reference to `notify_uninit'
journal-notify.c:(.text.startup+0xae0): undefined reference to `notify_uninit'
journal-notify.c:(.text.startup+0xaf9): undefined reference to `notify_init'
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'journal-notify' failed
make: *** [journal-notify] Error 1```

**Comment by eworm-de** [comment]
Possibly you need something like `libglib2.0-dev`? Just a guess, though.
What system is this?

**Comment by sherry13131** [comment]
I am using Ubuntu 18.04 in windows 10, which I downloaded from Microsoft store. I tried to install `libglib2.0-dev` but still doesn't work.

**Comment by eworm-de** [comment]
First of all... No idea if WSL supports showing notifications from `libnotify`.

As `pkg-config` obviously gives some output things *should* just work, at least for compilation. Ubuntu has something like `build-essentials`. Is that installed?

**Comment by sherry13131** [comment]
Yes, build-essential (12.4ubuntu1) and libnotify (0.7.7) both installed. Actually I want to use your journal-notify just for monitor a log file, and probably I will use -X EXECUTABLE: execute EXECUTABLE, do not show notification, in the command. So the notification pop up will not be important for now. Is there any way to do that and eliminate the problem when makefile?

**Comment by sherry13131** [comment]
I tried again in ubuntu 18.04 Virtual Machine, but still having the same problem.

**Comment by sherry13131** [comment]
I change a line in the Makefile, from
`journal-notify:
journal-notify.c journal-notify.h config.h version.h
$(CC) $(CFLAGS) $(LDFLAGS) -o journal-notify journal-notify.c` 
to 
`journal-notify: 
	$(CC) $(CFLAGS) $(LDFLAGS) -o journal-notify journal-notify.c journal-notify.h config.h version.h`
And it works now after changing this line

**Comment by eworm-de** [comment]
The header files are included from c file... This should not make a difference.

**Comment by yoanntalagrand** [comment]
I'm having the same issue when trying to make on Ubuntu:

gcc -std=c11 -O2 -fPIC -Wall -Werror -lsystemd -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,-z,now -Wl,-z,relro -pie -o journal-notify journal-notify.c
/usr/bin/ld: /tmp/ccANnj40.o: in function `notify':
journal-notify.c:(.text+0x28): undefined reference to `g_markup_escape_text'
/usr/bin/ld: journal-notify.c:(.text+0x43): undefined reference to `g_markup_escape_text'
/usr/bin/ld: journal-notify.c:(.text+0x72): undefined reference to `notify_notification_new'
/usr/bin/ld: journal-notify.c:(.text+0x8a): undefined reference to `notify_notification_set_timeout'
/usr/bin/ld: journal-notify.c:(.text+0x98): undefined reference to `notify_notification_set_urgency'
/usr/bin/ld: journal-notify.c:(.text+0xa2): undefined reference to `notify_notification_show'
/usr/bin/ld: journal-notify.c:(.text+0xb5): undefined reference to `g_type_check_instance_cast'
/usr/bin/ld: journal-notify.c:(.text+0xc0): undefined reference to `g_object_unref'
/usr/bin/ld: /tmp/ccANnj40.o: in function `main':
journal-notify.c:(.text.startup+0xe4): undefined reference to `sd_journal_open'
/usr/bin/ld: journal-notify.c:(.text.startup+0xf6): undefined reference to `sd_journal_seek_tail'
/usr/bin/ld: journal-notify.c:(.text.startup+0x108): undefined reference to `sd_journal_previous'
/usr/bin/ld: journal-notify.c:(.text.startup+0x1e2): undefined reference to `sd_journal_close'
/usr/bin/ld: journal-notify.c:(.text.startup+0x35a): undefined reference to `sd_journal_add_disjunction'
/usr/bin/ld: journal-notify.c:(.text.startup+0x3ce): undefined reference to `sd_journal_add_match'
/usr/bin/ld: journal-notify.c:(.text.startup+0x456): undefined reference to `sd_journal_add_conjunction'
/usr/bin/ld: journal-notify.c:(.text.startup+0x4fe): undefined reference to `sd_journal_next'
/usr/bin/ld: journal-notify.c:(.text.startup+0x520): undefined reference to `sd_journal_wait'
/usr/bin/ld: journal-notify.c:(.text.startup+0x58a): undefined reference to `sd_journal_get_data'
/usr/bin/ld: journal-notify.c:(.text.startup+0x5d5): undefined reference to `sd_journal_get_data'
/usr/bin/ld: journal-notify.c:(.text.startup+0x62f): undefined reference to `sd_journal_get_data'
/usr/bin/ld: journal-notify.c:(.text.startup+0x846): undefined reference to `notify_init'
/usr/bin/ld: journal-notify.c:(.text.startup+0x90b): undefined reference to `notify_uninit'
/usr/bin/ld: journal-notify.c:(.text.startup+0x924): undefined reference to `notify_init'
/usr/bin/ld: journal-notify.c:(.text.startup+0x940): undefined reference to `notify_uninit'
collect2: error: ld returned 1 exit status
make: *** [Makefile:23: journal-notify] Error 1
