### ISSUE TITLE
Update README to mention packages?

### ISSUE THREAD

**Issue by ambiamber** [eworm-de/journal-notify#5]
**Background / POV**

I got here because one of my computers had so-called "uncorrectable" btrfs errors which started on September 14, 2022 and it took until October 24, 2022 before I noticed.  I went looking for software that could improve the visibility of btrfs errors and found there was nothing "native". I saw suggestions to install all of Nagios, or set up systemd-timers or cron jobs to send mail. I kept looking and this package was the first I saw to present the errors as notifications.

**Regarding packages**

I did find https://aur.archlinux.org/packages/journal-notify which appears to be yours.
I started working on https://copr.fedorainfracloud.org/coprs/mettacrawler/journal-notify/
I checked for a PPA but my search didn't find one. https://launchpad.net/ubuntu/+ppas?name_filter=journal-notify
I could make a PPA.
I thinking having packages available would help consumers.  Admittedly it might bring more complaints.

**Question**

Should the README be updated to mention that there are packages?

Thanks

**Comment by eworm-de** [comment]
Feel free to submit a pull request... I think just above or below "upstream" would be fine.
